/**************************************************************************/
/* Copyright (c) 2022 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           20959

#define ENTRY_POINT_TTP_CONFIGURE_SP_ADJUSTMENT  0x040028d9 /* $_ttp_configure_sp_adjustment */
#define ENTRY_POINT_TTP_ADJUST_TTP_TIMESTAMP     0x040028eb /* $_ttp_adjust_ttp_timestamp */
#define ENTRY_POINT_TTP_GET_MSG_STATE_PARAMS     0x04002903 /* $_ttp_get_msg_state_params */
#define ENTRY_POINT_TTP_CONFIGURE_STATE_PARAMS   0x04002953 /* $_ttp_configure_state_params */
#define ENTRY_POINT_TTP_GET_STATE_PARAMS_STATUS  0x040029ff /* $_ttp_get_state_params_status */
#define ENTRY_POINT_GET_MSG_SP_ADJUSTMENT        0x040028bd /* $_ttp_get_msg_sp_adjustment */
#define ENTRY_POINT_TTP_GET_MSG_ADJUST_TTP_TIMESTAMP 0x040028cb /* $_ttp_get_msg_adjust_ttp_timestamp */
#define ENTRY_POINT_STREAM_SHORT_DOWNSTREAM_PROBE 0x04004e5d /* $_stream_short_downstream_probe */
#define ENTRY_POINT_STREAM_CALC_DOWNSTREAM_AMOUNT_WORDS_EX 0x04004ed5 /* $_stream_calc_downstream_amount_words_ex */
#define ENTRY_POINT_STREAM_TRANSFORM_FROM_BUFFER 0x04004f13 /* $_stream_transform_from_buffer */
#define ENTRY_POINT_CREATE_HOWLING_LIMITER_OP_PATCH 0x04006087 /* $_create_howling_limiter_op_patch */
#define ENTRY_POINT_INITIALIZE_HOWLING_LIMITER_OP_PATCH 0x040060c3 /* $_initialize_howling_limiter_op_patch */
#define ENTRY_POINT_CONFIGURE_HOWLING_LIMITER_OP_PATCH 0x040060cd /* $_configure_howling_limiter_op_patch */

#endif /* SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H */
